version: '3.9'

services:
  amr:
    image: sapienzanlp/usea-amr:1.0.1-cuda
    restart: always
    ports:
      - "${AMR_PORT}:80"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
