version: '3.9'

services:
  srl:
    image: sapienzanlp/usea-srl:1.0.3-dep-cuda
    restart: always
    ports:
      - "${SRL_PORT}:80"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
