version: '3.9'

services:
  wsd:
    image: sapienzanlp/usea-wsd:1.0.0-cuda
    restart: always
    ports:
      - "${WSD_PORT}:80"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
