version: '3.9'

services:
  orchestrator:
    image: sapienzanlp/usea-service:1.0.2
    ports:
      - "${ORCHESTRATOR_PORT}:8000"
    restart: always
    depends_on:
      - "preprocessing"
      - "wsd"
      - "srl"
      - "amr"
    environment:
      PREPROCESSING_ENDPOINT: "${PREPROCESSING_ENDPOINT}"
      WSD_ENDPOINT: "${WSD_ENDPOINT}"
      SRL_ENDPOINT: "${SRL_ENDPOINT}"
      AMR_ENDPOINT: "${AMR_ENDPOINT}"

  preprocessing:
    image: sapienzanlp/usea-preprocessing:1.0.0
    restart: always
    ports:
      - "${PREPROCESSING_PORT}:80"

  wsd:
    image: sapienzanlp/usea-wsd:1.0.0
    restart: always
    ports:
      - "${WSD_PORT}:80"

  srl:
    image: sapienzanlp/usea-srl:1.0.3-span
    restart: always
    ports:
      - "${SRL_PORT}:80"

  amr:
    image: sapienzanlp/usea-amr:1.0.1
    restart: always
    ports:
      - "${AMR_PORT}:80"
